name: Quick Tests on Push

on:
  push:
    branches-ignore:
      - main
      - develop
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'

env:
  PYTHON_VERSION: '3.11'
  POETRY_VERSION: '1.7.0'

jobs:
  quick-test:
    runs-on: ubuntu-latest
    name: Quick Unit Tests
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-quick-${{ hashFiles('**/poetry.lock') }}
      
      - name: Install dependencies
        run: poetry install --with dev
      
      - name: Run quick unit tests
        run: |
          poetry run pytest tests/unit \
            --tb=short \
            -x \
            --ff \
            -v
        env:
          YOUTUBE_API_KEY: 'dummy_test_key'
      
      - name: Quick lint check
        run: |
          poetry run black --check --diff src tests || true
          poetry run flake8 src tests --count --select=E9,F63,F7,F82 --show-source --statistics